language: php

#versions
php:
  - 5.5
  - 5.6
  - 7.1
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - curl -sSf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  
# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail on given environments
# fast_finish: If your build fails stop immediately
matrix:
  exclude:
    - php:  hhvm
  allow_failures:
    - php: 5.5
    - php: 5.6
    - php: hhvm

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: never
